/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package Menu;

import Connection.ConnectionJava;
import User.addUser;
import User.changeUser;
import User.loginForm;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AL-HACK3R
 */
public class tambahForm extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement ps;
    Statement stm;
    ResultSet rs;
    DefaultTableModel table;
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    /**
     * Creates new form tambahForm
     */
    public tambahForm() {
        initComponents();
        tampilData();
        setTitle("Tambah Data Judul");
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x,y);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        cancelBtn.setVisible(false);
        tambahBtn.setVisible(false);
        trash2.setVisible(false);
        trash3.setVisible(false);
        trash1.setVisible(false);
    }
    
    private void clear(){
        judulField2.setText("");
        namaPenulisField2.setText("");
        tahunField2.setText("");
        tampilData();
        judulField2.setEnabled(false);
        namaPenulisField2.setEnabled(false);
        tahunField2.setEnabled(false);
        trash2.setVisible(false);
        trash3.setVisible(false);
        trash1.setVisible(false);
        plusBtn.setVisible(true);
        cancelBtn.setVisible(false);
        tambahBtn.setVisible(false);
    }
    
    private void tampilData() {
        Object baris[] = {"Daftar Judul", "Nama Penulis"};
        table = new DefaultTableModel(null, baris);
        tabel.setModel(table);
        try {
            con = new ConnectionJava().ConnectDB();
            String select = "select * from judul order by id ASC";
            stm = con.createStatement();
            rs = stm.executeQuery(select);
            while(rs.next()) {
                String judul = rs.getString("judul");
                String nama = rs.getString("namaPenulis");
                String[] data = {judul, nama};
                table.addRow(data);
            }            
        }catch(SQLException e) {
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        judulField = new javax.swing.JTextField();
        namaPenulisField = new javax.swing.JTextField();
        tahunField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tambahBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        judulField2 = new javax.swing.JTextArea();
        namaPenulisField2 = new javax.swing.JTextField();
        tahunField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        plusBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        trash2 = new javax.swing.JButton();
        trash3 = new javax.swing.JButton();
        trash1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        addUser = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jLabel1.setText("Judul Skripsi");

        jLabel2.setText("Nama Penulis");

        jLabel3.setText("Tahun");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Judul Skripsi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Nama Penulis");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Tanggal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        tambahBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tambahBtn.setText("TAMBAH DATA");
        tambahBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tambahBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tambahBtnMouseExited(evt);
            }
        });
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });
        getContentPane().add(tambahBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, 35));

        judulField2.setColumns(20);
        judulField2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        judulField2.setLineWrap(true);
        judulField2.setRows(5);
        judulField2.setEnabled(false);
        judulField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                judulField2KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(judulField2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 930, 70));

        namaPenulisField2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        namaPenulisField2.setEnabled(false);
        namaPenulisField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namaPenulisField2KeyPressed(evt);
            }
        });
        getContentPane().add(namaPenulisField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 280, 35));

        tahunField2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tahunField2.setEnabled(false);
        tahunField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tahunField2KeyPressed(evt);
            }
        });
        getContentPane().add(tahunField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 160, 35));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabel.setRowHeight(20);
        tabel.setRowMargin(2);
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 1050, 340));

        plusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/plus.png"))); // NOI18N
        plusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBtnActionPerformed(evt);
            }
        });
        getContentPane().add(plusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 35, 35));

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exit.png"))); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 35, 35));

        trash2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bin.png"))); // NOI18N
        trash2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trash2ActionPerformed(evt);
            }
        });
        getContentPane().add(trash2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 35, 35));

        trash3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bin.png"))); // NOI18N
        trash3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trash3ActionPerformed(evt);
            }
        });
        getContentPane().add(trash3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 35, 35));

        trash1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bin.png"))); // NOI18N
        trash1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trash1ActionPerformed(evt);
            }
        });
        getContentPane().add(trash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 130, 35, 35));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tambahJudul.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        jMenu5.setText("Menu");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Tambah Judul");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem2.setText("Cari Judul");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar2.add(jMenu5);

        addUser.setText("User");

        jMenuItem4.setText("Tambah User");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        addUser.add(jMenuItem4);

        jMenuItem5.setText("Ubah Data User");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        addUser.add(jMenuItem5);

        jMenuItem6.setText("Logout");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        addUser.add(jMenuItem6);

        jMenuBar2.add(addUser);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        String judul = judulField2.getText();
        String nama = namaPenulisField2.getText();
        String tahun = tahunField2.getText();
        if(judul.equals("")){
            JOptionPane.showMessageDialog(null, "Judul Skripsi Tidak Boleh Kosong");
            judulField2.requestFocus(true);
        }
        if(nama.equals("")){
            JOptionPane.showMessageDialog(null, "Nama Penulis Tidak Boleh Kosong");
            namaPenulisField2.requestFocus(true);
        }
        if(tahun.equals("")){
            JOptionPane.showMessageDialog(null, "Tahun Tidak Boleh Kosong");
            tahunField2.requestFocus(true);
        }
        if((!judul.equals("")) && (!nama.equals("")) && (!tahun.equals(""))){
            try{
                con = new ConnectionJava().ConnectDB();
                String check = "SELECT * FROM judul WHERE judul=?";
                ps = con.prepareStatement(check);
                ps.setString(1, judul);
                rs = ps.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Judul Sudah Dimasukkan Sebelumnya");
                    judulField2.requestFocus(true);
                }else{
                    try{
                        String check2 = "SELECT * FROM judul WHERE namaPenulis=? and tahun=?";
                        ps = con.prepareStatement(check2);
                        ps.setString(1, nama);
                        ps.setString(2, tahun);
                        rs = ps.executeQuery();
                        if(rs.next()){
                            JOptionPane.showMessageDialog(null, "Penulis Tidak Boleh Memasukkan Judul Sebanyak 2x");
                            namaPenulisField2.requestFocus(true);
                        }else{
                            try{
                                String tambah = "INSERT INTO `judul` (id, judul, namaPenulis, tahun) VALUES" + "(null, '"+judul+"','"+nama+"','"+tahun+"')";
                                stm = con.createStatement();
                                stm.executeUpdate(tambah);
                                JOptionPane.showMessageDialog(null, "Berhasil Menambah Data Judul Skripsi");
                                clear();
                                tampilData();
                            }catch(SQLException | HeadlessException e){
                                JOptionPane.showMessageDialog(null, "Gagal Menambah Data Judul Skripsi");
                            }
                        }
                    }catch(SQLException | HeadlessException e){
                        JOptionPane.showMessageDialog(null, "Gagal Melakukan Verifikasi Data Penulis");
                    }
                }
            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Gagal Melakukan Verifikasi Data Judul Skripsi");
            }
        }
    }//GEN-LAST:event_tambahBtnActionPerformed
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
        new tambahForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        new tampilForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        
    }//GEN-LAST:event_jMenu5ActionPerformed
    
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
        new addUser().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.dispose();
        new changeUser().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.dispose();
        new loginForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    
    private void tambahBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahBtnMouseEntered
        tambahBtn.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_tambahBtnMouseEntered

    private void tambahBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahBtnMouseExited
        tambahBtn.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_tambahBtnMouseExited

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        judulField2.setEnabled(false);
        namaPenulisField2.setEnabled(false);
        tahunField2.setEnabled(false);
        cancelBtn.setVisible(false);
        tambahBtn.setVisible(false);
        clear();
        trash2.setVisible(false);
        trash3.setVisible(false);
        trash1.setVisible(false);
        plusBtn.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void plusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBtnActionPerformed
        judulField2.setEnabled(true);
        namaPenulisField2.setEnabled(true);
        tahunField2.setEnabled(true);
        cancelBtn.setVisible(true);
        tambahBtn.setVisible(true);
        plusBtn.setVisible(false);
    }//GEN-LAST:event_plusBtnActionPerformed

    private void trash1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trash1ActionPerformed
        judulField2.setText("");
        trash1.setVisible(false);
    }//GEN-LAST:event_trash1ActionPerformed

    private void trash2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trash2ActionPerformed
        namaPenulisField2.setText("");
        trash2.setVisible(false);
    }//GEN-LAST:event_trash2ActionPerformed

    private void trash3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trash3ActionPerformed
        tahunField2.setText("");
        trash3.setVisible(false);
    }//GEN-LAST:event_trash3ActionPerformed

    private void namaPenulisField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaPenulisField2KeyPressed
        trash2.setVisible(true);
        if(namaPenulisField2.getText().isEmpty()){
            trash2.setVisible(false);
        }
    }//GEN-LAST:event_namaPenulisField2KeyPressed

    private void tahunField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tahunField2KeyPressed
        trash3.setVisible(true);
        if(tahunField2.getText().isEmpty()){
            trash3.setVisible(false);
        }
    }//GEN-LAST:event_tahunField2KeyPressed

    private void judulField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_judulField2KeyPressed
        trash1.setVisible(true);
        if(judulField2.getText().isEmpty()){
            trash1.setVisible(false);
        }
    }//GEN-LAST:event_judulField2KeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu addUser;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField judulField;
    private javax.swing.JTextArea judulField2;
    private javax.swing.JTextField namaPenulisField;
    private javax.swing.JTextField namaPenulisField2;
    private javax.swing.JButton plusBtn;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tahunField;
    private javax.swing.JTextField tahunField2;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JButton trash1;
    private javax.swing.JButton trash2;
    private javax.swing.JButton trash3;
    // End of variables declaration//GEN-END:variables
}
